services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    container_name: monitoring-ppa-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: monitoring-ppa-web
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: monitoring-ppa-db
    environment:
      MYSQL_DATABASE: monitoring_ppa
      MYSQL_USER: monitoring
      MYSQL_PASSWORD: monitoring
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - monitoring_ppa_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: monitoring-ppa-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: monitoring
      PMA_PASSWORD: monitoring
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  monitoring_ppa_db_data:
